"""kie.ai 图像模型参数表——由 tools/refresh_kie_models.py 自动生成，请勿手改。

各模型的参考图字段名、分辨率字段名与取值都不一致，这里按官方文档逐个登记。
共 54 个模型。
"""

KIE_IMAGE_MODELS = {'bytedance/seedream-v4-edit': {'aspect_field': None,
                                'aspect_style': None,
                                'aspects': [],
                                'image_field': 'image_urls',
                                'image_is_list': True,
                                'label': 'Seedream4.0 - Edit',
                                'max_references': 10,
                                'resolution_field': 'image_resolution',
                                'resolutions': ['1K', '2K', '4K'],
                                'supports_prompt': True},
 'bytedance/seedream-v4-text-to-image': {'aspect_field': None,
                                         'aspect_style': None,
                                         'aspects': [],
                                         'image_field': None,
                                         'image_is_list': False,
                                         'label': 'Seedream4.0 - Text to Image',
                                         'max_references': 0,
                                         'resolution_field': 'image_resolution',
                                         'resolutions': ['1K', '2K', '4K'],
                                         'supports_prompt': True},
 'flux-2/flex-image-to-image': {'aspect_field': 'aspect_ratio',
                                'aspect_style': 'ratio',
                                'aspects': ['1:1', '4:3', '3:4', '16:9', '9:16', '3:2', '2:3'],
                                'image_field': 'input_urls',
                                'image_is_list': True,
                                'label': 'Flux-2 - Image to Image',
                                'max_references': 8,
                                'resolution_field': 'resolution',
                                'resolutions': ['1K', '2K'],
                                'supports_prompt': True},
 'flux-2/flex-text-to-image': {'aspect_field': 'aspect_ratio',
                               'aspect_style': 'ratio',
                               'aspects': ['1:1', '4:3', '3:4', '16:9', '9:16', '3:2', '2:3'],
                               'image_field': None,
                               'image_is_list': False,
                               'label': 'Flux-2 - Text to Image',
                               'max_references': 0,
                               'resolution_field': 'resolution',
                               'resolutions': ['1K', '2K'],
                               'supports_prompt': True},
 'flux-2/pro-image-to-image': {'aspect_field': 'aspect_ratio',
                               'aspect_style': 'ratio',
                               'aspects': ['1:1', '4:3', '3:4', '16:9', '9:16', '3:2', '2:3'],
                               'image_field': 'input_urls',
                               'image_is_list': True,
                               'label': 'Flux-2 - Pro Image to Image',
                               'max_references': 8,
                               'resolution_field': 'resolution',
                               'resolutions': ['1K', '2K'],
                               'supports_prompt': True},
 'flux-2/pro-text-to-image': {'aspect_field': 'aspect_ratio',
                              'aspect_style': 'ratio',
                              'aspects': ['1:1', '4:3', '3:4', '16:9', '9:16', '3:2', '2:3'],
                              'image_field': None,
                              'image_is_list': False,
                              'label': 'Flux-2 - Pro Text to Image',
                              'max_references': 0,
                              'resolution_field': 'resolution',
                              'resolutions': ['1K', '2K'],
                              'supports_prompt': True},
 'google/imagen4': {'aspect_field': 'aspect_ratio',
                    'aspect_style': 'ratio',
                    'aspects': ['1:1', '16:9', '9:16', '3:4', '4:3'],
                    'image_field': None,
                    'image_is_list': False,
                    'label': 'Google - imagen4',
                    'max_references': 0,
                    'resolution_field': None,
                    'resolutions': [],
                    'supports_prompt': True},
 'google/imagen4-fast': {'aspect_field': 'aspect_ratio',
                         'aspect_style': 'ratio',
                         'aspects': ['1:1', '16:9', '9:16', '3:4', '4:3'],
                         'image_field': None,
                         'image_is_list': False,
                         'label': 'Google - imagen4-fast',
                         'max_references': 0,
                         'resolution_field': None,
                         'resolutions': [],
                         'supports_prompt': True},
 'google/imagen4-ultra': {'aspect_field': 'aspect_ratio',
                          'aspect_style': 'ratio',
                          'aspects': ['1:1', '16:9', '9:16', '3:4', '4:3'],
                          'image_field': None,
                          'image_is_list': False,
                          'label': 'Google - imagen4-ultra',
                          'max_references': 0,
                          'resolution_field': None,
                          'resolutions': [],
                          'supports_prompt': True},
 'google/nano-banana': {'aspect_field': 'aspect_ratio',
                        'aspect_style': 'ratio',
                        'aspects': ['1:1', '9:16', '16:9', '3:4', '4:3', '3:2', '2:3', '5:4', '4:5', '21:9'],
                        'image_field': None,
                        'image_is_list': False,
                        'label': 'Google - Nano Banana',
                        'max_references': 0,
                        'resolution_field': None,
                        'resolutions': [],
                        'supports_prompt': True},
 'google/nano-banana-edit': {'aspect_field': 'aspect_ratio',
                             'aspect_style': 'ratio',
                             'aspects': ['1:1',
                                         '9:16',
                                         '16:9',
                                         '3:4',
                                         '4:3',
                                         '3:2',
                                         '2:3',
                                         '5:4',
                                         '4:5',
                                         '21:9'],
                             'image_field': 'image_urls',
                             'image_is_list': True,
                             'label': 'Google - Nano Banana Edit',
                             'max_references': 10,
                             'resolution_field': None,
                             'resolutions': [],
                             'supports_prompt': True},
 'gpt-image-2-5-flare-image-to-image': {'aspect_field': 'aspect_ratio',
                                        'aspect_style': 'ratio',
                                        'aspects': ['1:1',
                                                    '3:2',
                                                    '2:3',
                                                    '4:3',
                                                    '3:4',
                                                    '16:9',
                                                    '9:16',
                                                    '21:9',
                                                    '27:16',
                                                    '16:27',
                                                    '9:8',
                                                    '8:9'],
                                        'image_field': 'input_urls',
                                        'image_is_list': True,
                                        'label': 'GPT Image 2.5 Flare 图生图',
                                        'max_references': 16,
                                        'resolution_field': 'resolution',
                                        'resolutions': ['1K', '2K', '4K'],
                                        'supports_prompt': True},
 'gpt-image-2-5-flare-text-to-image': {'aspect_field': 'aspect_ratio',
                                       'aspect_style': 'ratio',
                                       'aspects': ['1:1',
                                                   '3:2',
                                                   '2:3',
                                                   '4:3',
                                                   '3:4',
                                                   '16:9',
                                                   '9:16',
                                                   '21:9',
                                                   '27:16',
                                                   '16:27',
                                                   '9:8',
                                                   '8:9'],
                                       'image_field': None,
                                       'image_is_list': False,
                                       'label': 'GPT Image 2.5 Flare 文生图',
                                       'max_references': 0,
                                       'resolution_field': 'resolution',
                                       'resolutions': ['1K', '2K', '4K'],
                                       'supports_prompt': True},
 'gpt-image-2-5-sunburst-image-to-image': {'aspect_field': 'aspect_ratio',
                                           'aspect_style': 'ratio',
                                           'aspects': ['1:1',
                                                       '3:2',
                                                       '2:3',
                                                       '4:3',
                                                       '3:4',
                                                       '16:9',
                                                       '9:16',
                                                       '21:9',
                                                       '27:16',
                                                       '16:27',
                                                       '9:8',
                                                       '8:9'],
                                           'image_field': 'input_urls',
                                           'image_is_list': True,
                                           'label': 'GPT Image 2.5 Sunburst 图生图',
                                           'max_references': 16,
                                           'resolution_field': 'resolution',
                                           'resolutions': ['1K', '2K', '4K'],
                                           'supports_prompt': True},
 'gpt-image-2-5-sunburst-text-to-image': {'aspect_field': 'aspect_ratio',
                                          'aspect_style': 'ratio',
                                          'aspects': ['1:1',
                                                      '3:2',
                                                      '2:3',
                                                      '4:3',
                                                      '3:4',
                                                      '16:9',
                                                      '9:16',
                                                      '21:9',
                                                      '27:16',
                                                      '16:27',
                                                      '9:8',
                                                      '8:9'],
                                          'image_field': None,
                                          'image_is_list': False,
                                          'label': 'GPT Image 2.5 Sunburst 文生图',
                                          'max_references': 0,
                                          'resolution_field': 'resolution',
                                          'resolutions': ['1K', '2K', '4K'],
                                          'supports_prompt': True},
 'gpt-image-2-image-to-image': {'aspect_field': 'aspect_ratio',
                                'aspect_style': 'ratio',
                                'aspects': ['1:1',
                                            '3:2',
                                            '2:3',
                                            '4:3',
                                            '3:4',
                                            '5:4',
                                            '4:5',
                                            '16:9',
                                            '9:16',
                                            '2:1',
                                            '1:2',
                                            '3:1',
                                            '1:3',
                                            '21:9',
                                            '9:21'],
                                'image_field': 'input_urls',
                                'image_is_list': True,
                                'label': 'GPT Image 2 图生图',
                                'max_references': 16,
                                'resolution_field': 'resolution',
                                'resolutions': ['1K', '2K', '4K'],
                                'supports_prompt': True},
 'gpt-image-2-text-to-image': {'aspect_field': 'aspect_ratio',
                               'aspect_style': 'ratio',
                               'aspects': ['1:1',
                                           '3:2',
                                           '2:3',
                                           '4:3',
                                           '3:4',
                                           '5:4',
                                           '4:5',
                                           '16:9',
                                           '9:16',
                                           '2:1',
                                           '1:2',
                                           '3:1',
                                           '1:3',
                                           '21:9',
                                           '9:21'],
                               'image_field': None,
                               'image_is_list': False,
                               'label': 'GPT Image 2 文生图',
                               'max_references': 0,
                               'resolution_field': 'resolution',
                               'resolutions': ['1K', '2K', '4K'],
                               'supports_prompt': True},
 'gpt-image/1.5-image-to-image': {'aspect_field': 'aspect_ratio',
                                  'aspect_style': 'ratio',
                                  'aspects': ['1:1', '2:3', '3:2'],
                                  'image_field': 'input_urls',
                                  'image_is_list': True,
                                  'label': 'GPT Image1.5 图生图',
                                  'max_references': 16,
                                  'resolution_field': None,
                                  'resolutions': [],
                                  'supports_prompt': True},
 'gpt-image/1.5-text-to-image': {'aspect_field': 'aspect_ratio',
                                 'aspect_style': 'ratio',
                                 'aspects': ['1:1', '2:3', '3:2'],
                                 'image_field': None,
                                 'image_is_list': False,
                                 'label': 'GPT Image1.5 文生图',
                                 'max_references': 0,
                                 'resolution_field': None,
                                 'resolutions': [],
                                 'supports_prompt': True},
 'grok-imagine-image-2-0/image-edit': {'aspect_field': 'aspect_ratio',
                                       'aspect_style': 'ratio',
                                       'aspects': ['1:1', '2:3', '3:2', '16:9', '9:16'],
                                       'image_field': 'image_urls',
                                       'image_is_list': True,
                                       'label': 'Grok Imagine Image 2.0 图片编辑',
                                       'max_references': 5,
                                       'resolution_field': None,
                                       'resolutions': [],
                                       'supports_prompt': True},
 'grok-imagine-image-2-0/segment-edit': {'aspect_field': None,
                                         'aspect_style': None,
                                         'aspects': [],
                                         'image_field': None,
                                         'image_is_list': False,
                                         'label': 'Grok Imagine Image 2.0 Segment Edit',
                                         'max_references': 0,
                                         'resolution_field': None,
                                         'resolutions': [],
                                         'supports_prompt': True},
 'grok-imagine-image-2-0/segment-map': {'aspect_field': None,
                                        'aspect_style': None,
                                        'aspects': [],
                                        'image_field': None,
                                        'image_is_list': False,
                                        'label': 'Grok Imagine Image 2.0 Segment Map',
                                        'max_references': 0,
                                        'resolution_field': None,
                                        'resolutions': [],
                                        'supports_prompt': False},
 'grok-imagine-image-2-0/text-to-image': {'aspect_field': 'aspect_ratio',
                                          'aspect_style': 'ratio',
                                          'aspects': ['1:1', '2:3', '3:2', '16:9', '9:16'],
                                          'image_field': None,
                                          'image_is_list': False,
                                          'label': 'Grok Imagine Image 2.0 文生图',
                                          'max_references': 0,
                                          'resolution_field': None,
                                          'resolutions': [],
                                          'supports_prompt': True},
 'grok-imagine/image-to-image': {'aspect_field': None,
                                 'aspect_style': None,
                                 'aspects': [],
                                 'image_field': 'image_urls',
                                 'image_is_list': True,
                                 'label': 'Grok Imagine 图生图',
                                 'max_references': 5,
                                 'resolution_field': None,
                                 'resolutions': [],
                                 'supports_prompt': True},
 'grok-imagine/text-to-image': {'aspect_field': 'aspect_ratio',
                                'aspect_style': 'ratio',
                                'aspects': ['2:3', '3:2', '1:1', '16:9', '9:16'],
                                'image_field': None,
                                'image_is_list': False,
                                'label': 'Grok Imagine 文生图',
                                'max_references': 0,
                                'resolution_field': None,
                                'resolutions': [],
                                'supports_prompt': True},
 'ideogram/character': {'aspect_field': 'image_size',
                        'aspect_style': 'preset',
                        'aspects': ['square',
                                    'square_hd',
                                    'portrait_4_3',
                                    'portrait_16_9',
                                    'landscape_4_3',
                                    'landscape_16_9'],
                        'image_field': 'reference_image_urls',
                        'image_is_list': True,
                        'label': 'Ideogram 角色图像生成',
                        'max_references': 10,
                        'resolution_field': None,
                        'resolutions': [],
                        'supports_prompt': True},
 'ideogram/character-edit': {'aspect_field': None,
                             'aspect_style': None,
                             'aspects': [],
                             'image_field': 'image_url',
                             'image_is_list': False,
                             'label': 'Ideogram 角色编辑',
                             'max_references': 1,
                             'resolution_field': None,
                             'resolutions': [],
                             'supports_prompt': True},
 'ideogram/character-remix': {'aspect_field': 'image_size',
                              'aspect_style': 'preset',
                              'aspects': ['square',
                                          'square_hd',
                                          'portrait_4_3',
                                          'portrait_16_9',
                                          'landscape_4_3',
                                          'landscape_16_9'],
                              'image_field': 'image_url',
                              'image_is_list': False,
                              'label': 'Ideogram 角色重混',
                              'max_references': 1,
                              'resolution_field': None,
                              'resolutions': [],
                              'supports_prompt': True},
 'ideogram/v3-edit': {'aspect_field': None,
                      'aspect_style': None,
                      'aspects': [],
                      'image_field': 'image_url',
                      'image_is_list': False,
                      'label': 'Ideogram V3 图像编辑',
                      'max_references': 1,
                      'resolution_field': None,
                      'resolutions': [],
                      'supports_prompt': True},
 'ideogram/v3-remix': {'aspect_field': 'image_size',
                       'aspect_style': 'preset',
                       'aspects': ['square',
                                   'square_hd',
                                   'portrait_4_3',
                                   'portrait_16_9',
                                   'landscape_4_3',
                                   'landscape_16_9'],
                       'image_field': 'image_url',
                       'image_is_list': False,
                       'label': 'Ideogram V3 混合',
                       'max_references': 1,
                       'resolution_field': None,
                       'resolutions': [],
                       'supports_prompt': True},
 'ideogram/v3-text-to-image': {'aspect_field': 'image_size',
                               'aspect_style': 'preset',
                               'aspects': ['square',
                                           'square_hd',
                                           'portrait_4_3',
                                           'portrait_16_9',
                                           'landscape_4_3',
                                           'landscape_16_9'],
                               'image_field': None,
                               'image_is_list': False,
                               'label': 'Ideogram V3 文生图',
                               'max_references': 0,
                               'resolution_field': None,
                               'resolutions': [],
                               'supports_prompt': True},
 'nano-banana-2': {'aspect_field': 'aspect_ratio',
                   'aspect_style': 'ratio',
                   'aspects': ['1:1',
                               '2:3',
                               '3:2',
                               '1:4',
                               '4:1',
                               '3:4',
                               '4:3',
                               '4:5',
                               '5:4',
                               '1:8',
                               '8:1',
                               '9:16',
                               '16:9',
                               '21:9'],
                   'image_field': 'image_input',
                   'image_is_list': True,
                   'label': 'Google - Nano Banana 2',
                   'max_references': 14,
                   'resolution_field': 'resolution',
                   'resolutions': ['1K', '2K', '4K'],
                   'supports_prompt': True},
 'nano-banana-2-lite': {'aspect_field': 'aspect_ratio',
                        'aspect_style': 'ratio',
                        'aspects': ['1:1',
                                    '1:4',
                                    '1:8',
                                    '2:3',
                                    '3:2',
                                    '3:4',
                                    '4:1',
                                    '4:3',
                                    '4:5',
                                    '5:4',
                                    '8:1',
                                    '9:16',
                                    '16:9',
                                    '21:9'],
                        'image_field': 'image_urls',
                        'image_is_list': True,
                        'label': 'Google - Nano Banana 2 Lite',
                        'max_references': 10,
                        'resolution_field': None,
                        'resolutions': [],
                        'supports_prompt': True},
 'nano-banana-pro': {'aspect_field': 'aspect_ratio',
                     'aspect_style': 'ratio',
                     'aspects': ['1:1', '2:3', '3:2', '3:4', '4:3', '4:5', '5:4', '9:16', '16:9', '21:9'],
                     'image_field': 'image_input',
                     'image_is_list': True,
                     'label': 'Google - Nano Banana Pro',
                     'max_references': 8,
                     'resolution_field': 'resolution',
                     'resolutions': ['1K', '2K', '4K'],
                     'supports_prompt': True},
 'qwen/image-edit': {'aspect_field': 'image_size',
                     'aspect_style': 'preset',
                     'aspects': ['square',
                                 'square_hd',
                                 'portrait_4_3',
                                 'portrait_16_9',
                                 'landscape_4_3',
                                 'landscape_16_9'],
                     'image_field': 'image_url',
                     'image_is_list': False,
                     'label': 'Qwen 图片编辑',
                     'max_references': 1,
                     'resolution_field': None,
                     'resolutions': [],
                     'supports_prompt': True},
 'qwen/image-to-image': {'aspect_field': None,
                         'aspect_style': None,
                         'aspects': [],
                         'image_field': 'image_url',
                         'image_is_list': False,
                         'label': 'Qwen 图生图',
                         'max_references': 1,
                         'resolution_field': None,
                         'resolutions': [],
                         'supports_prompt': True},
 'qwen/text-to-image': {'aspect_field': 'image_size',
                        'aspect_style': 'preset',
                        'aspects': ['square',
                                    'square_hd',
                                    'portrait_4_3',
                                    'portrait_16_9',
                                    'landscape_4_3',
                                    'landscape_16_9'],
                        'image_field': None,
                        'image_is_list': False,
                        'label': 'Qwen 文生图',
                        'max_references': 0,
                        'resolution_field': None,
                        'resolutions': [],
                        'supports_prompt': True},
 'qwen2-1/image-to-image': {'aspect_field': 'aspect_ratio',
                            'aspect_style': 'ratio',
                            'aspects': ['1:1', '4:3', '3:4', '3:2', '2:3', '16:9', '9:16', '21:9', '9:21'],
                            'image_field': 'image_urls',
                            'image_is_list': True,
                            'label': 'Qwen 2.1 图生图',
                            'max_references': 10,
                            'resolution_field': 'resolution',
                            'resolutions': ['1K', '2K'],
                            'supports_prompt': True},
 'qwen2-1/text-to-image': {'aspect_field': 'aspect_ratio',
                           'aspect_style': 'ratio',
                           'aspects': ['1:1', '4:3', '3:4', '3:2', '2:3', '16:9', '9:16', '21:9', '9:21'],
                           'image_field': None,
                           'image_is_list': False,
                           'label': 'Qwen 2.1 文生图',
                           'max_references': 0,
                           'resolution_field': 'resolution',
                           'resolutions': ['1K', '2K'],
                           'supports_prompt': True},
 'qwen2/image-edit': {'aspect_field': 'image_size',
                      'aspect_style': 'ratio',
                      'aspects': ['1:1', '3:4', '4:3', '9:16', '16:9'],
                      'image_field': None,
                      'image_is_list': False,
                      'label': 'Qwen2 文生图',
                      'max_references': 0,
                      'resolution_field': None,
                      'resolutions': [],
                      'supports_prompt': True},
 'qwen3-pro/text-to-image': {'aspect_field': 'image_size',
                             'aspect_style': 'ratio',
                             'aspects': ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
                             'image_field': None,
                             'image_is_list': False,
                             'label': 'Qwen3 Pro 文生图',
                             'max_references': 0,
                             'resolution_field': 'resolution',
                             'resolutions': ['1K', '2K'],
                             'supports_prompt': True},
 'qwen3/image-to-image': {'aspect_field': 'image_size',
                          'aspect_style': 'ratio',
                          'aspects': ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
                          'image_field': 'image_urls',
                          'image_is_list': True,
                          'label': 'Qwen3 Image to Image',
                          'max_references': 3,
                          'resolution_field': 'resolution',
                          'resolutions': ['1K', '2K'],
                          'supports_prompt': True},
 'qwen3/pro-image-to-image': {'aspect_field': 'image_size',
                              'aspect_style': 'ratio',
                              'aspects': ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
                              'image_field': 'image_urls',
                              'image_is_list': True,
                              'label': 'Qwen3 Pro 图生图',
                              'max_references': 3,
                              'resolution_field': 'resolution',
                              'resolutions': ['1K', '2K'],
                              'supports_prompt': True},
 'qwen3/text-to-image': {'aspect_field': 'image_size',
                         'aspect_style': 'ratio',
                         'aspects': ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
                         'image_field': None,
                         'image_is_list': False,
                         'label': 'Qwen3 文生图',
                         'max_references': 0,
                         'resolution_field': 'resolution',
                         'resolutions': ['1K', '2K'],
                         'supports_prompt': True},
 'recraft/crisp-upscale': {'aspect_field': None,
                           'aspect_style': None,
                           'aspects': [],
                           'image_field': 'image',
                           'image_is_list': False,
                           'label': 'Recraft 图像优化',
                           'max_references': 1,
                           'resolution_field': None,
                           'resolutions': [],
                           'supports_prompt': False},
 'recraft/remove-background': {'aspect_field': None,
                               'aspect_style': None,
                               'aspects': [],
                               'image_field': 'image',
                               'image_is_list': False,
                               'label': 'Recraft 背景移除',
                               'max_references': 1,
                               'resolution_field': None,
                               'resolutions': [],
                               'supports_prompt': False},
 'seedream/4.5-edit': {'aspect_field': 'aspect_ratio',
                       'aspect_style': 'ratio',
                       'aspects': ['1:1', '4:3', '3:4', '16:9', '9:16', '2:3', '3:2', '21:9'],
                       'image_field': 'image_urls',
                       'image_is_list': True,
                       'label': 'Seedream4.5 - Edit',
                       'max_references': 14,
                       'resolution_field': None,
                       'resolutions': [],
                       'supports_prompt': True},
 'seedream/4.5-text-to-image': {'aspect_field': 'aspect_ratio',
                                'aspect_style': 'ratio',
                                'aspects': ['1:1', '4:3', '3:4', '16:9', '9:16', '2:3', '3:2', '21:9'],
                                'image_field': None,
                                'image_is_list': False,
                                'label': 'Seedream4.5 - Text to Image',
                                'max_references': 0,
                                'resolution_field': None,
                                'resolutions': [],
                                'supports_prompt': True},
 'seedream/5-lite-text-to-image': {'aspect_field': 'aspect_ratio',
                                   'aspect_style': 'ratio',
                                   'aspects': ['1:1', '4:3', '3:4', '16:9', '9:16', '2:3', '3:2', '21:9'],
                                   'image_field': None,
                                   'image_is_list': False,
                                   'label': 'Seedream5.0 Lite - Text to Image',
                                   'max_references': 0,
                                   'resolution_field': None,
                                   'resolutions': [],
                                   'supports_prompt': True},
 'seedream/5-pro-image-to-image': {'aspect_field': 'aspect_ratio',
                                   'aspect_style': 'ratio',
                                   'aspects': ['1:1', '4:3', '3:4', '16:9', '9:16', '2:3', '3:2', '21:9'],
                                   'image_field': 'image_urls',
                                   'image_is_list': True,
                                   'label': 'Seedream5.0 Pro - Image to Image',
                                   'max_references': 10,
                                   'resolution_field': None,
                                   'resolutions': [],
                                   'supports_prompt': True},
 'seedream/5-pro-text-to-image': {'aspect_field': 'aspect_ratio',
                                  'aspect_style': 'ratio',
                                  'aspects': ['1:1', '4:3', '3:4', '16:9', '9:16', '2:3', '3:2', '21:9'],
                                  'image_field': None,
                                  'image_is_list': False,
                                  'label': 'Seedream5.0 Pro - Text to Image',
                                  'max_references': 0,
                                  'resolution_field': None,
                                  'resolutions': [],
                                  'supports_prompt': True},
 'topaz/image-upscale': {'aspect_field': None,
                         'aspect_style': None,
                         'aspects': [],
                         'image_field': 'image_url',
                         'image_is_list': False,
                         'label': 'Topaz 图像优化',
                         'max_references': 1,
                         'resolution_field': None,
                         'resolutions': [],
                         'supports_prompt': False},
 'wan/2-7-image-pro': {'aspect_field': 'aspect_ratio',
                       'aspect_style': 'ratio',
                       'aspects': ['1:1', '16:9', '4:3', '21:9', '3:4', '9:16', '8:1', '1:8'],
                       'image_field': 'input_urls',
                       'image_is_list': True,
                       'label': 'Wan 2.7 Image Pro',
                       'max_references': 9,
                       'resolution_field': 'resolution',
                       'resolutions': ['1K', '2K', '4K'],
                       'supports_prompt': True},
 'z-image': {'aspect_field': 'aspect_ratio',
             'aspect_style': 'ratio',
             'aspects': ['1:1', '4:3', '3:4', '16:9', '9:16'],
             'image_field': None,
             'image_is_list': False,
             'label': 'Z-Image',
             'max_references': 0,
             'resolution_field': None,
             'resolutions': [],
             'supports_prompt': True}}
